[build]
  base = "client"
  command = "CI=false npm install && CI=false npm run build"
  publish = "build"

[build.environment]
  REACT_APP_API_URL = "https://nutripal-server-uf5h.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
